### ISSUE TITLE
Use getters in structs

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/exasol-rest-api#12]
## Problem

We don't have getters for variables in structs and it should be possible to add them.

**Comment by Nicoretti** [comment]
Ticket is to fuzzy, it is unclear which structs need to be addressed? For addressing all structs additional work would on top of the getters, e.g. `MarshalJSON` [interface](https://pkg.go.dev/encoding/json#Marshaler) needs to be implemented, would be needed to be done. Because private fields do not get serialized by the "default" marshal implementation.
